### PR TITLE
updated transition from Basics to Prep

### PR DESCRIPTION
**Pull request by jackin614**
Pulled transition statement from near beginning.   Did some cleanup.

### CODE REVIEW

**Comment by jackin614** [comment]
I'm not sure this is still needed.  I think everything has been merged.   Can you tell?

**Comment by carmendeardo** [comment]
Well you did a merge 13 hours ago and I can see new content on the main
Shoulders document including some of my stuff.  So if it looks good to you,
we should be OK.  I see there were merge conflicts but I assume you managed
those.  If the document doesn't look right, there's a revert but I also
assume you are keeping some local copies and not completely depending on
GitHub :-)

Thanks Jack!

My plan is to write next about some Bell Labs experiences as they relate to
"modern" concepts such as SRE and ChaosMonkey and how DevOps-ish things
have been done in the past but perhaps just not marketed.

After that, I was thinking maybe we should allow the merges to catch up and
take stock because some of the cards in my backlog may have already been
covered, at least to some extent.

**Comment by jackin614** [comment]
I watched several videos on YouTube yesterday and think I am probably mostly using the tool right.   But am still struggling with some of the nuances, particularly since none of the compare stuff works on Shoulders.  

I am keeping local copies, you bet!   I'm WFH today too, in case you want to chat IRL.  

I'm working on the Math part right now.

I'm thinking soon we should review the content together to talk about what is here and how/where it would go together.   For example, not sure what to do with the Dickens piece yet.    I think it might be good to work from some hard copies to map what goes where and any significant re-structuring.  (I feel like a piece is missing, but not sure what, yet.)

**Comment by carmendeardo** [comment]
ok sounds good.  I agree that we probably have both written about similar
stuff so far and perhaps you need me to branch more into new areas that
haven't been covered yet.   I'm off Friday and have some times we can talk.

**Comment by jackin614** [comment]
Cool, I'll print everything tomorrow.  Perhaps 2 copies (if you want 1)?
The Math stuff, is that OK to drop in with minor edits?  Do we need to reference Lee, get permission to use, or anything like that?

**Comment by carmendeardo** [comment]
thanks, Yes I could use a copy printed.

The math stuff is good to go - Lee gave me permission

**Comment by jackin614** [comment]
OK, we will need to talk about that permission a little more, but not now.   Basically if he (or IBM) consider that intellectual property (IP) then we'll need something in writing, and will have to annotate our use accordingly.   If it's more loose, then we might be able to get by as a reference with light editing, or just use it with some "heavy" editing.   NBD, we'll figure it out.

**Comment by carmendeardo** [comment]
ok - I don't think IBM was ever involved in this and he doesn't work for
them any longer.   I do think we should reference him.

**Comment by jackin614** [comment]
Cool!

**Pull request merged**
